### ISSUE TITLE
Do some setup

### ISSUE THREAD

**Issue by wurli** [DfE-R-Community/ggdfe#1]
Hi @scookedfe, thought I'd put in an issue sooner rather than later so you can see how they work 😃 

For setup, I reckon the following is probably a good checklist:

* Write a `README.md` to explain the purpose of the project
* Add the functionality which you've already put together
* Make sure `devtools::check()` completes okay and doesn't throw any errors/warnings/notes. This is _the_ function you run to check your code doesn't have any issues, and the checks have to pass for the package to make it to CRAN, so worth getting on top of in the early stages

Once you've done the above, make a pull request into `main` and we can close this issue when that PR gets merged 😄

**Comment by scookedfe** [comment]
Hi @wurli 

I've pushed the initial files and added some documentation. It's nothing major but it's a start! It passes `devtools::check()` with no errors/warnings/notes.

I also pushed from rstudio without a branch and it's gone straight into `main` - sorry! The pull req is from an update to the readme.

Ta
